#214 restructure database for different types of vehicles
blumilksoftware/e-motion-api pull request #224
Opened 2024-04-27 10:40 UTC by JakubKermes

This should close #214 .

2024-05-05 11:31 UTC, AleksandraKozubal approved these changes

2024-05-06 06:22 UTC, kamilpiech97 requested changes

2024-05-06 06:22 UTC, kamilpiech97 commented on app/Models/CityProvider.php
> +    }
HasMany? or HasOne?

2024-05-06 06:22 UTC, kamilpiech97 commented on database/seeders/ServiceSeeder.php
> +        Service::create(["type" => "motorscooter"]);
I would like to move that into Enum.

2024-05-13 07:18 UTC, kamilpiech97 approved these changes

2024-05-13 07:49 UTC, EwelinaSkrzypacz approved these changes

2024-05-13 08:03 UTC, merged